package cz.ixi.fusionweb.drools.rules;

rule "Create notification if too many customer registrations"
no-loop
when
	not CustomerRegistrationTooManyReported() over window:time(1h)
	ArrayList(size >= 2) from collect( CustomerRegistrationEvent() over window:time(1h))
	//ArrayList(size >= 100) from collect( CustomerRegistrationEvent() over window:time(1h))
then
	channels["tooManyCustomerRegistrations"].send("too many");
	insert(new CustomerRegistrationTooManyReported());
end

rule "Customer Registrations Too Many Reported reported"
when
  CustomerRegistrationTooManyReported() over window:time(1h)
then
end
