package cz.ixi.fusionweb.drools.rules;

import cz.ixi.fusionweb.drools.model.NavigationEvent;
import cz.ixi.fusionweb.drools.model.ProductNavigationEvent;
import cz.ixi.fusionweb.drools.model.ProductSearchEvent;
import cz.ixi.fusionweb.drools.model.ProductSearchUnsuccessfulEvent;
import cz.ixi.fusionweb.drools.model.ProductSearchSuccessfulEvent;
import cz.ixi.fusionweb.drools.model.CustomerRegistrationEvent;
import cz.ixi.fusionweb.drools.model.CustomerRegistrationUnsuccessfulEvent;
import cz.ixi.fusionweb.drools.model.DiscussionEntryEvent;
import cz.ixi.fusionweb.drools.model.CustomerLogInEvent;
import cz.ixi.fusionweb.drools.model.OrderCreatedEvent;
import cz.ixi.fusionweb.drools.model.ProductBoughtEvent;
import cz.ixi.fusionweb.entities.Product;
import cz.ixi.fusionweb.entities.Notification;
import cz.ixi.fusionweb.entities.NotificationSeverity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.List;
import java.util.Date;


declare NavigationEvent
	@role(event)
end

declare ProductNavigationEvent
	@role(event)
	@expires( 24h )
end

declare ProductSearchEvent
	@role(event)
end

declare ProductSearchSuccessfulEvent 
	@role(event)
end

declare ProductSearchUnsuccessfulEvent 
	@role(event)
end

declare CustomerRegistrationEvent 
	@role(event)
end

declare CustomerRegistrationUnsuccessfulEvent 
	@role(event)
end

declare DiscussionEntryEvent 
	@role(event)
end
		
declare CustomerLogInEvent 
	@role(event)
end

declare OrderCreatedEvent 
	@role(event)
end

declare ProductBoughtEvent 
	@role(event)
	@expires( 24h )
end

declare SearchedText
	@role(fact)
	text : String
end

declare SearchedTextReported
	@role(event)
	text : String
end

declare CurrentMainProduct
	@role(fact)
	id : Integer
end

declare CustomerRegistrationTooManyReported
	@role(event)
end

declare ProductVisitedButNotBoughtReported
	@role(event)
	@expires( 24h )
	productId: Integer
end

declare ManyProductPurchasesReported
	@role(event)
	productId: Integer
end

