package cz.ixi.fusionweb.drools.rules;

rule "Choose first main product at the start."
when
	not CurrentMainProduct()
then
	insert(new CurrentMainProduct(30));
	channels["defaultLayout"].send(30);
end

rule "Change main product if there is a better one."
no-loop
//timer (int: 30m)
when
	exists (ProductNavigationEvent() over window:time(1h) from entry-point "ProductNavigationStream" )
	$current : CurrentMainProduct()
	$mostVisitedProductId : Integer() from accumulate ($pne : ProductNavigationEvent($id : id) 
														      over window:time(1h) 
														      from entry-point "ProductNavigationStream", 
														      mostVisited($pne))
 	eval ($current.getId() != $mostVisitedProductId)	 
then
	modify ($current) {
		setId($mostVisitedProductId);
	}
	channels["defaultLayout"].send($mostVisitedProductId);
end

