package cz.ixi.fusionweb.drools.rules;

import cz.ixi.fusionweb.drools.model.NavigationEvent;
import cz.ixi.fusionweb.drools.model.ProductNavigationEvent;
import cz.ixi.fusionweb.web.layout.DefaultLayoutController;
import cz.ixi.fusionweb.entities.Product;
import cz.ixi.fusionweb.ejb.ProductBean;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.List;

declare ProductNavigationEvent
	@role(event)
end

rule "print what is inserted"
when
	$o: Object()
then
	System.out.println("Found fact: " + $o);
end

// TODO: add time window, entrypoint and timer
rule "change main product if there is better one"
no-loop
when
	exists (ProductNavigationEvent())
	$dlc : DefaultLayoutController()
	$products : ProductBean()
	$mostVisitedProductId : Integer() from accumulate ($pne : ProductNavigationEvent($id : id), mostVisited($pne))
 	eval ($dlc.getMainProduct().getId() != $mostVisitedProductId)	 
then
	System.out.println("Setting of new main product, previous was: " + $dlc.getMainProduct());
  	modify($dlc){
  		setMainProduct($products.find($mostVisitedProductId));
  	}
    System.out.println("Setting of new main product, new is:       " + $dlc.getMainProduct());
end

