package cz.ixi.fusionweb.drools.rules;

rule "No UserActionsEvent"
when
	GeneralUserActionEvent($username: username, username!=null)
	not UserActionsEvent(username == $username)
then
	insert(new UserActionsEvent($username, new ArrayList()));
	System.out.println("new UserActionsEvent for " + $username);
end

rule "Add userAction to UserActionsEvent"
no-loop
when
	$navEvent: GeneralUserActionEvent($username: username, username!=null)
	$userNav: UserActionsEvent(username == $username)
then
	$userNav.getActions().add($navEvent);
	
	System.out.println("UserActionsEvent added " + $navEvent);
end
