package cz.ixi.fusionweb.drools.rules;


rule "Create notification if there is visited, but not bought product."
no-loop
when
	ProductNavigationEvent($productId: productId, $productName: productName) 
	not ProductVisitedButNotBoughtReported(productId == $productId) over window:time(1h)
	$visited: Number() from accumulate( $pne: ProductNavigationEvent(productId == $productId) over window:time(1h),  count( $pne ) )
	Number( $visited - intValue >= 100 ) from accumulate( $pbe: ProductBoughtEvent(productId == $productId) over window:time(1h),  count( $pbe ) )

then
	insert(new ProductVisitedButNotBoughtReported($productId));
	channels["notificationsGeneral"].send(new Notification(NotificationSeverity.SEVERE, new Date(), 
	"In the last hour was product "+ $productId +":" +$productName + " been visited many times, but not bought a lot." ));
end

rule "Product Visited But Not Bought Reported"
when
  ProductVisitedButNotBoughtReported() over window:time(1h)
then
end


