package cz.ixi.fusionweb.drools.rules;



rule "Create notification if there is visited, but not bought product."
no-loop
when
	ProductNavigationEvent($productId: id, $productName: productName) from entry-point "ProductNavigationStream" 
	not ProductVisitedButNotBoughtReported(productId == $productId) over window:time(1h)
	$visited: Number() from accumulate( $pne: ProductNavigationEvent(id == $productId) over window:time(1h) from entry-point "ProductNavigationStream",  count( $pne ) )
	Number( $visited - intValue >= 100 ) from accumulate( $pbe: ProductBoughtEvent(productId == $productId) over window:time(1h),  count( $pbe ) )

then
	insert(new ProductVisitedButNotBoughtReported($productId));
	channels["notificationsGeneral"].send(new Notification(NotificationSeverity.SEVERE, new Date(), 
	"In the last hour was product "+ $productId +":" +$productName + " been visited many times, but not bought a lot." ));
end

rule "Product Visited But Not Bought Reported"
when
  ProductVisitedButNotBoughtReported() over window:time(1h)
then
end

rule "Product Visited But NosdfReported"
when
  ProductBoughtEvent() over window:time(1h)
then
end

rule "Product Visited But Notsdf Reported"
when
  ProductNavigationEvent()  over window:time(1h) from entry-point "ProductNavigationStream" 
then
end

