package cz.ixi.fusionweb.drools.rules;


rule "Report most visited category in the last hour if any."
timer (cron:0 0 */1 * * ?)
when
	$mostVisitedCategoryEvent : CategoryNavigationEvent() from accumulate ($pne : CategoryNavigationEvent() 
														      over window:time(1h)
														      mostVisitedCategory($pne))
then
	if ($mostVisitedCategoryEvent.getProductCategoryId() != -1) {
		channels["statisticsHourly"].send("The most visited category in the menu in the last hour was "+ $mostVisitedCategoryEvent.getCategoryName() + "(" +$mostVisitedCategoryEvent.getProductCategoryId() + ")." );
	} else {
		channels["statisticsHourly"].send("No category in the menu was visited in the last hour." );
	}
end


rule "Report most visited category in the last day if any."
timer (cron:0 0 0 */1 * ?)
when
	$mostVisitedCategoryEvent : CategoryNavigationEvent() from accumulate ($pne : CategoryNavigationEvent() 
														      over window:time(24h)
														      mostVisitedCategory($pne))
then
	if ($mostVisitedCategoryEvent.getProductCategoryId() != -1) {
		channels["statisticsDaily"].send("The most visited category in the menu in the last day was "+ $mostVisitedCategoryEvent.getCategoryName() + "(" +$mostVisitedCategoryEvent.getProductCategoryId() + ")." );
	} else {
		channels["statisticsDaily"].send("No category in the menu was visited in the last day." );
	}
	
end

